name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
      
env:
  MAJOR_VERSION: 1
  MINOR_VERSION: 0
  MICRO_VERSION: 0

jobs:

  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s app/unittest -p "*.py"
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name}}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name}}:${{ env.MAJOR_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name}}:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name}}:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.MICRO_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name}}:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.MICRO_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name}}:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.MICRO_VERSION }}-${{ env.SHORT_SHA }}